// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//玩家状态
type PlayerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID  string `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Type int32  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"` // 0:Player login, 1:PlayerJoin, 2:PlayerLeav
	Code int32  `protobuf:"varint,3,opt,name=Code,proto3" json:"Code,omitempty"` // 错误代码  0:成功, 其他:错误
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (x *PlayerState) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PlayerState) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

//玩家信息
type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID  string `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type int32  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

//玩家列表
type PlayerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*PlayerInfo `protobuf:"bytes,1,rep,name=Players,proto3" json:"Players,omitempty"`
}

func (x *PlayerList) Reset() {
	*x = PlayerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerList) ProtoMessage() {}

func (x *PlayerList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerList.ProtoReflect.Descriptor instead.
func (*PlayerList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerList) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

//玩家登录
type PlayerLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Pass string `protobuf:"bytes,2,opt,name=Pass,proto3" json:"Pass,omitempty"`
	Type int32  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *PlayerLogin) Reset() {
	*x = PlayerLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogin) ProtoMessage() {}

func (x *PlayerLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogin.ProtoReflect.Descriptor instead.
func (*PlayerLogin) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerLogin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerLogin) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

func (x *PlayerLogin) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

//玩家加入
type PlayerJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PInfo *PlayerInfo `protobuf:"bytes,1,opt,name=PInfo,proto3" json:"PInfo,omitempty"`
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerJoin) GetPInfo() *PlayerInfo {
	if x != nil {
		return x.PInfo
	}
	return nil
}

//玩家离开
type PlayerLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID    string `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Reason int32  `protobuf:"varint,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerLeave) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (x *PlayerLeave) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

//玩家离开列表
type PLeaveList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PLeaves []*PlayerLeave `protobuf:"bytes,1,rep,name=PLeaves,proto3" json:"PLeaves,omitempty"`
}

func (x *PLeaveList) Reset() {
	*x = PLeaveList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PLeaveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLeaveList) ProtoMessage() {}

func (x *PLeaveList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLeaveList.ProtoReflect.Descriptor instead.
func (*PLeaveList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{6}
}

func (x *PLeaveList) GetPLeaves() []*PlayerLeave {
	if x != nil {
		return x.PLeaves
	}
	return nil
}

//其他请求
type PlayerOther struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RType int32 `protobuf:"varint,1,opt,name=RType,proto3" json:"RType,omitempty"` //请求类型
}

func (x *PlayerOther) Reset() {
	*x = PlayerOther{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerOther) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOther) ProtoMessage() {}

func (x *PlayerOther) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOther.ProtoReflect.Descriptor instead.
func (*PlayerOther) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerOther) GetRType() int32 {
	if x != nil {
		return x.RType
	}
	return 0
}

//玩家请求消息
type PlayerReqMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID string `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	// Types that are assignable to Data:
	//	*PlayerReqMsg_PLogin
	//	*PlayerReqMsg_PJoin
	//	*PlayerReqMsg_PLeave
	//	*PlayerReqMsg_POther
	Data isPlayerReqMsg_Data `protobuf_oneof:"Data"`
}

func (x *PlayerReqMsg) Reset() {
	*x = PlayerReqMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerReqMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReqMsg) ProtoMessage() {}

func (x *PlayerReqMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReqMsg.ProtoReflect.Descriptor instead.
func (*PlayerReqMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerReqMsg) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (m *PlayerReqMsg) GetData() isPlayerReqMsg_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *PlayerReqMsg) GetPLogin() *PlayerLogin {
	if x, ok := x.GetData().(*PlayerReqMsg_PLogin); ok {
		return x.PLogin
	}
	return nil
}

func (x *PlayerReqMsg) GetPJoin() *PlayerJoin {
	if x, ok := x.GetData().(*PlayerReqMsg_PJoin); ok {
		return x.PJoin
	}
	return nil
}

func (x *PlayerReqMsg) GetPLeave() *PlayerLeave {
	if x, ok := x.GetData().(*PlayerReqMsg_PLeave); ok {
		return x.PLeave
	}
	return nil
}

func (x *PlayerReqMsg) GetPOther() *PlayerOther {
	if x, ok := x.GetData().(*PlayerReqMsg_POther); ok {
		return x.POther
	}
	return nil
}

type isPlayerReqMsg_Data interface {
	isPlayerReqMsg_Data()
}

type PlayerReqMsg_PLogin struct {
	PLogin *PlayerLogin `protobuf:"bytes,2,opt,name=PLogin,proto3,oneof"` //player login 对应玩家登录
}

type PlayerReqMsg_PJoin struct {
	PJoin *PlayerJoin `protobuf:"bytes,3,opt,name=PJoin,proto3,oneof"` //player join 对应玩家加入
}

type PlayerReqMsg_PLeave struct {
	PLeave *PlayerLeave `protobuf:"bytes,4,opt,name=PLeave,proto3,oneof"` //player leave 对应玩家离开
}

type PlayerReqMsg_POther struct {
	POther *PlayerOther `protobuf:"bytes,5,opt,name=POther,proto3,oneof"` //player other 其他请求类型
}

func (*PlayerReqMsg_PLogin) isPlayerReqMsg_Data() {}

func (*PlayerReqMsg_PJoin) isPlayerReqMsg_Data() {}

func (*PlayerReqMsg_PLeave) isPlayerReqMsg_Data() {}

func (*PlayerReqMsg_POther) isPlayerReqMsg_Data() {}

//玩家响应消息
type PlayerResMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID string `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	// Types that are assignable to Data:
	//	*PlayerResMsg_PStatus
	//	*PlayerResMsg_PInfo
	//	*PlayerResMsg_PList
	//	*PlayerResMsg_PJoin
	//	*PlayerResMsg_PLeave
	//	*PlayerResMsg_PLList
	Data isPlayerResMsg_Data `protobuf_oneof:"Data"`
}

func (x *PlayerResMsg) Reset() {
	*x = PlayerResMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerResMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResMsg) ProtoMessage() {}

func (x *PlayerResMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResMsg.ProtoReflect.Descriptor instead.
func (*PlayerResMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerResMsg) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (m *PlayerResMsg) GetData() isPlayerResMsg_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *PlayerResMsg) GetPStatus() *PlayerState {
	if x, ok := x.GetData().(*PlayerResMsg_PStatus); ok {
		return x.PStatus
	}
	return nil
}

func (x *PlayerResMsg) GetPInfo() *PlayerInfo {
	if x, ok := x.GetData().(*PlayerResMsg_PInfo); ok {
		return x.PInfo
	}
	return nil
}

func (x *PlayerResMsg) GetPList() *PlayerList {
	if x, ok := x.GetData().(*PlayerResMsg_PList); ok {
		return x.PList
	}
	return nil
}

func (x *PlayerResMsg) GetPJoin() *PlayerJoin {
	if x, ok := x.GetData().(*PlayerResMsg_PJoin); ok {
		return x.PJoin
	}
	return nil
}

func (x *PlayerResMsg) GetPLeave() *PlayerLeave {
	if x, ok := x.GetData().(*PlayerResMsg_PLeave); ok {
		return x.PLeave
	}
	return nil
}

func (x *PlayerResMsg) GetPLList() *PLeaveList {
	if x, ok := x.GetData().(*PlayerResMsg_PLList); ok {
		return x.PLList
	}
	return nil
}

type isPlayerResMsg_Data interface {
	isPlayerResMsg_Data()
}

type PlayerResMsg_PStatus struct {
	PStatus *PlayerState `protobuf:"bytes,2,opt,name=PStatus,proto3,oneof"` //状态信息
}

type PlayerResMsg_PInfo struct {
	PInfo *PlayerInfo `protobuf:"bytes,3,opt,name=PInfo,proto3,oneof"` //单个player
}

type PlayerResMsg_PList struct {
	PList *PlayerList `protobuf:"bytes,4,opt,name=PList,proto3,oneof"` //player列表
}

type PlayerResMsg_PJoin struct {
	PJoin *PlayerJoin `protobuf:"bytes,5,opt,name=PJoin,proto3,oneof"` //player join  notify
}

type PlayerResMsg_PLeave struct {
	PLeave *PlayerLeave `protobuf:"bytes,6,opt,name=PLeave,proto3,oneof"` //player leave notify
}

type PlayerResMsg_PLList struct {
	PLList *PLeaveList `protobuf:"bytes,7,opt,name=PLList,proto3,oneof"` //player leave list
}

func (*PlayerResMsg_PStatus) isPlayerResMsg_Data() {}

func (*PlayerResMsg_PInfo) isPlayerResMsg_Data() {}

func (*PlayerResMsg_PList) isPlayerResMsg_Data() {}

func (*PlayerResMsg_PJoin) isPlayerResMsg_Data() {}

func (*PlayerResMsg_PLeave) isPlayerResMsg_Data() {}

func (*PlayerResMsg_PLList) isPlayerResMsg_Data() {}

//系统消息
type SysMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID     string `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"` //内容
}

func (x *SysMsg) Reset() {
	*x = SysMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysMsg) ProtoMessage() {}

func (x *SysMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysMsg.ProtoReflect.Descriptor instead.
func (*SysMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{10}
}

func (x *SysMsg) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (x *SysMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

//聊天消息
type TalkMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID     string `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"` //聊天内容
}

func (x *TalkMsg) Reset() {
	*x = TalkMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkMsg) ProtoMessage() {}

func (x *TalkMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkMsg.ProtoReflect.Descriptor instead.
func (*TalkMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{11}
}

func (x *TalkMsg) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (x *TalkMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x47, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x46, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x36, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x49, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50,
	0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69,
	0x6e, 0x12, 0x24, 0x0a, 0x05, 0x50, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x50, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x37, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x37, 0x0a, 0x0a, 0x50, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x07, 0x50, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65,
	0x52, 0x07, 0x50, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x54, 0x79, 0x70, 0x65, 0x22, 0xd1,
	0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x4d, 0x73, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x49,
	0x44, 0x12, 0x29, 0x0a, 0x06, 0x50, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x50, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x05,
	0x50, 0x4a, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x50,
	0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x50, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x48, 0x00, 0x52, 0x06, 0x50, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12,
	0x29, 0x0a, 0x06, 0x50, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x06, 0x50, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0xa2, 0x02, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x07, 0x50, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x07, 0x50, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x50, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x48, 0x00, 0x52, 0x05, 0x50, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x05, 0x50, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x50, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x50, 0x4a, 0x6f, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69,
	0x6e, 0x48, 0x00, 0x52, 0x05, 0x50, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x50, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x48, 0x00, 0x52, 0x06, 0x50,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x50, 0x4c, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x50, 0x4c, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x79, 0x73, 0x4d, 0x73,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x50, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x35, 0x0a,
	0x07, 0x54, 0x61, 0x6c, 0x6b, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x42, 0x0c, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0xaa, 0x02, 0x02,
	0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_msg_proto_goTypes = []interface{}{
	(*PlayerState)(nil),  // 0: pb.PlayerState
	(*PlayerInfo)(nil),   // 1: pb.PlayerInfo
	(*PlayerList)(nil),   // 2: pb.PlayerList
	(*PlayerLogin)(nil),  // 3: pb.PlayerLogin
	(*PlayerJoin)(nil),   // 4: pb.PlayerJoin
	(*PlayerLeave)(nil),  // 5: pb.PlayerLeave
	(*PLeaveList)(nil),   // 6: pb.PLeaveList
	(*PlayerOther)(nil),  // 7: pb.PlayerOther
	(*PlayerReqMsg)(nil), // 8: pb.PlayerReqMsg
	(*PlayerResMsg)(nil), // 9: pb.PlayerResMsg
	(*SysMsg)(nil),       // 10: pb.SysMsg
	(*TalkMsg)(nil),      // 11: pb.TalkMsg
}
var file_msg_proto_depIdxs = []int32{
	1,  // 0: pb.PlayerList.Players:type_name -> pb.PlayerInfo
	1,  // 1: pb.PlayerJoin.PInfo:type_name -> pb.PlayerInfo
	5,  // 2: pb.PLeaveList.PLeaves:type_name -> pb.PlayerLeave
	3,  // 3: pb.PlayerReqMsg.PLogin:type_name -> pb.PlayerLogin
	4,  // 4: pb.PlayerReqMsg.PJoin:type_name -> pb.PlayerJoin
	5,  // 5: pb.PlayerReqMsg.PLeave:type_name -> pb.PlayerLeave
	7,  // 6: pb.PlayerReqMsg.POther:type_name -> pb.PlayerOther
	0,  // 7: pb.PlayerResMsg.PStatus:type_name -> pb.PlayerState
	1,  // 8: pb.PlayerResMsg.PInfo:type_name -> pb.PlayerInfo
	2,  // 9: pb.PlayerResMsg.PList:type_name -> pb.PlayerList
	4,  // 10: pb.PlayerResMsg.PJoin:type_name -> pb.PlayerJoin
	5,  // 11: pb.PlayerResMsg.PLeave:type_name -> pb.PlayerLeave
	6,  // 12: pb.PlayerResMsg.PLList:type_name -> pb.PLeaveList
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PLeaveList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerOther); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerReqMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerResMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_msg_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*PlayerReqMsg_PLogin)(nil),
		(*PlayerReqMsg_PJoin)(nil),
		(*PlayerReqMsg_PLeave)(nil),
		(*PlayerReqMsg_POther)(nil),
	}
	file_msg_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*PlayerResMsg_PStatus)(nil),
		(*PlayerResMsg_PInfo)(nil),
		(*PlayerResMsg_PList)(nil),
		(*PlayerResMsg_PJoin)(nil),
		(*PlayerResMsg_PLeave)(nil),
		(*PlayerResMsg_PLList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
